name: Build and test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  publish:
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - id: get_version
      uses: battila7/get-version-action@v2

    - name: Debug
      run: echo ${{ steps.get_version.outputs.version-without-v }}
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore
      run: msbuild -t:restore

    - name: Pack
      run: msbuild -t:Pack -p:NuspecProperties="version=${{ steps.get_version.outputs.version-without-v }}" -p:PackageVersion=${{ steps.get_version.outputs.version-without-v }}

    - name: Publish packages
      run: dotnet nuget push ./artifacts/**${{ steps.vars.outputs.tag }}**.nupkg --source nuget.org --api-key ${{secrets.NUGET_TOKEN}}