name: Build

on:
  push:
    tags: '**'

  publish:
    runs-on: ubuntu-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Determine version
      run: echo "::set-env name=VERSION::$(git describe --tags --dirty)"

    - name: Pack
      run: dotnet pack --output ./artifacts --configuration Release -p:Version=$VERSION

    - name: Publish packages
      run: dotnet nuget push ./artifacts/**.nupkg --source nuget.org --api-key ${{secrets.NUGET_TOKEN}}