name: Publish

on:
  push:
    tags: '**'

jobs:
  publish:
    runs-on: windows-latest

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: true

    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Restore
      run: msbuild -t:restore

    - name: Pack
      run: msbuild -t:Pack -p:NuspecProperties="version=${{ steps.vars.outputs.tag }}" -p:PackageVersion=${{ steps.vars.outputs.tag }}

    - name: Publish packages
      run: dotnet nuget push ./artifacts/**${{ steps.vars.outputs.tag }}**.nupkg --source nuget.org --api-key ${{secrets.NUGET_TOKEN}}
